baseURL = 'https://gregmillerga.me/'
languageCode = 'en-us'
title = 'Greg Miller - Game Designer'
theme = "re-terminal"
pagination.pagerSize = 5

[params]
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  themeColor = "pink"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 3

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = true

  # if your resource directory contains an image called `cover.(jpg|png|webp)`,
  # then the file will be used as a cover automatically.
  # With this option you don't have to put the `cover` param in a front-matter.
  autoCover = true

  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"


  # whether to show a page's estimated reading time
  # readingTime = true # default

  # whether to show a table of contents
  # can be overridden in a page's front-matter
  # Toc = false # default

  # set title for the table of contents
  # can be overridden in a page's front-matter
  # TocTitle = "Table of Contents" # default

[caches]
  [caches.images]
    dir = ':cacheDir/images'


[params.twitter]
  # set Twitter handles for Twitter cards
  # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
  # do not include @
  creator = "GregMillerGame"

[languages]
  [languages.en.params]
    languageName = "English"
    title = "Greg Miller - Game Designer"
    subtitle = "Personal Portfolio for Greg Miller"
    owner = "GregMillerGame"
    keywords = ""
    copyright = "©️ GregMillerGame"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"
    minuteReadingTime = "min read"
    words = "words"

    [languages.en.params.logo]
      logoText = "Greg Miller - Game Designer"
      logoHomeLink = "/"

    [languages.en.menu]
      # Submenus is available since v2.1.0
      # [[languages.en.menu.main]]
      #   identifier = "submenuParent"
      #   name = "Submenu"
      # [[languages.en.menu.main]]
      #   parent = "submenuParent"
      #   identifier = "anItem"
      #   name = "AnItem"
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About Me!"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Game Showcase"
      [[languages.en.menu.main]]
        parent = "showcase"
        name = "Wizard101"
        url = "/games/wizard101"
      [[languages.en.menu.main]]
        identifier = "SocialMedia"
        name = "My Socials"
      [[languages.en.menu.main]]
        parent = "SocialMedia"
        name = "Twitter"
        url = "https://x.com/GregMillerGame"
      [[languages.en.menu.main]]
        parent = "SocialMedia"
        name = "Youtube"
        url = "https://www.youtube.com/@GregMillerGame"
      [[languages.en.menu.main]]
        parent = "SocialMedia"
        name = "Itch.io"
        url = "https://gregtmiller.itch.io/"
      [[languages.en.menu.main]]
        parent = "SocialMedia"
        name = "Linkedin"
        url = "https://www.linkedin.com/in/gregory-t-miller/"